baseurl = "/"
languageCode = "en-us"
paginate = 5
theme = "hello-friend"

[params]
# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "posts"

# "light" or "dark"
defaultTheme = "dark"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 2

# Show reading time in minutes for posts
showReadingTime = false

# Show table of contents at the top of your posts (defaults to false)
# Alternatively, add this param to post front matter for specific posts
# toc = true

# Show full page content in RSS feed items
#(default is Description or Summary metadata in the front matter)
# rssFullText = true

[languages]
[languages.en]
copyright = ""
dateFormatList = "2006-01-02"
dateFormatSingle = "2006-01-02"
keywords = ""
menuMore = "Show more"
minuteReadingTime = "min read"
newerPosts = "Newer posts"
olderPosts = "Older posts"
readMore = "Read more"
readOtherPosts = "Read other posts"
subtitle = "A simple theme for Hugo"
title = "Hello Friend"
writtenBy = "Written by"
# leave empty to disable, enter display text to enable
# lastModDisplay = ""

[languages.en.params.logo]
logoHomeLink = "/"
logoText = "riweston"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "post"
name = "posts"
url = "/post"
